#!/usr/bin/env bash

set -eo pipefail

#####################################################################
# Helper functions start with _ and aren't listed in help menu.
#####################################################################

function _test {
  echo "test ${@}"
}

#####################################################################
#                      TASKS
#####################################################################

function cmd { # Example command placeholder
  _test "${@}"
}


#####################################################################
#                  Don't touch
#####################################################################

function _help { # Help menu
  printf "\n%s <task> [args]\n\nTasks:\n" "${0}"
  cat "$0" | grep "function [a-z]" | cut -d' ' -f2- | awk '{printf "\t%-20s\t%s\n", $1, substr($0,index($0,$4))}'
}

function _zsh_setup { # For ZSH auto-completion: source <(./run _zsh_setup)
  compl_list=("$(cat "$0" | grep "function [a-z]" | cut -d' ' -f2 | xargs)")
  echo "_compl() { compadd $compl_list }"
  echo "compdef _compl run"
  exit 0
}

TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-_help}"
