#!/usr/bin/env bash

set -eo pipefail

DC="${DC:-exec}"

# If we're running in CI we need to disable TTY allocation for docker-compose
# commands that enable it by default, such as exec and run.
TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _dc {
  docker-compose "${DC}" ${TTY} "${@}"
}

function _build_run_down {
  docker-compose build
  docker-compose run ${TTY} "${@}"
  docker-compose down
}

# -----------------------------------------------------------------------------

function cmd { # Run any command you want in the web container
  _dc web "${@}"
}

function flask { # Run any Flask commands
  cmd flask "${@}"
}

function psql { # Connect to PostgreSQL with psql
  # shellcheck disable=SC1091
  . .env
  _dc postgres psql -U "${POSTGRES_USER}" "${@}"
}

function redis-cli {  # Connect to Redis with redis-cli
  _dc redis redis-cli "${@}"
}

function pip3:install { # Install pip3 dependencies and write lock file
  _build_run_down web bin/pip3-install
}

function clean { # Remove cache and other machine generates files
  rm -rf .pytest_cache/ public/* .coverage celerybeat-schedule
  touch public/.keep
}


# -----------------------------------------------------------------------------

function help { # Help menu
  printf "\n%s <task> [args]\n\nTasks:\n" "${0}"

  #compgen -A function | grep -v "^_" | cat -n
  cat "$0" | grep "function [a-z]" | cut -d' ' -f2- | awk '{printf "\t%-20s\t%s\n", $1, substr($0,index($0,$4))}'

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

function zsh_setup { # For ZSH auto-completion: source <(./run zsh_setup)
  compl_list=("$(cat "$0" | grep "function [a-z]" | cut -d' ' -f2 | xargs)")
  echo "_compl() { compadd $compl_list }"
  echo "compdef _compl run"
  exit 0
}

TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
